name: Bicep-CI-Tests
on:
  push:
    branches: [ main ]
    paths:
    - '**.bicep'
    - '**.json'
  workflow_dispatch:
    
jobs:

  Bicep-ValidationTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: ARM TTK
      uses: docker://ghcr.io/github/super-linter:slim-v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        VALIDATE_JSON: true
    - name: Bicep Build
      uses: aliencube/bicep-build-actions@v0.3
      with:
        files: '**/*.bicep'

  Bicep-CI-Tests-Sub-Scope:
    needs: Bicep-ValidationTests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SP_GLOBALBAO }}
    - name: Bicep CI Tests
      id: bicepCI
      continue-on-error: true
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment sub create -f ./Bicep/modules/sub_main.bicep -l australiaeast -p ./Bicep/modules/sub_main_params.json --what-if
    - name: Sleep for 30s
      if: ${{ steps.bicepCI.outcome == 'failure' && steps.bicepCI.conclusion == 'success' }}
      uses: juliangruber/sleep-action@v1
      with:
        time: 30s
    - name: Bicep CI Retry
      if: ${{ steps.bicepCI.outcome == 'failure' && steps.bicepCI.conclusion == 'success' }}
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment sub create -f ./Bicep/modules/sub_main.bicep -l australiaeast -p ./Bicep/modules/sub_main_params.json --what-if

  Bicep-CI-Tests-MG-Scope:
    needs: Bicep-CI-Tests-Sub-Scope
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SP_GLOBALBAO }}
    - name: Bicep CI Tests
      id: bicepCI
      continue-on-error: true
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment mg create -f ./Bicep/modules/mg_main.bicep -l australiaeast -m TEST -p ./Bicep/modules/mg_main_params.json --what-if
    - name: Sleep for 30s
      if: ${{ steps.bicepCI.outcome == 'failure' && steps.bicepCI.conclusion == 'success' }}
      uses: juliangruber/sleep-action@v1
      with:
        time: 30s
    - name: Bicep CI Retry
      if: ${{ steps.bicepCI.outcome == 'failure' && steps.bicepCI.conclusion == 'success' }}
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment mg create -f ./Bicep/modules/mg_main.bicep -l australiaeast -m TEST -p ./Bicep/modules/mg_main_params.json --what-if
